FROM alpine:3.16
RUN apk add --no-cache \
    python3 \
    py3-pip \
    py3-wheel \
    py3-requests \
    py3-feedparser

COPY ./api.py ./rss_crawler.py /app/
WORKDIR /app

CMD ["python3", "rss_crawler.py"]
