FROM alpine:3.16
RUN apk add --no-cache \
    python3 \
    py3-pip \
    py3-wheel \
    py3-requests \
    py3-beautifulsoup4

RUN pip install \
    requests-html \
    jieba

COPY ./tokenizer.py /app/tokenizer.py
WORKDIR /app

CMD ["python3", "tokenizer.py"]
